### PR TITLE
Organize unit tests

### PR DESCRIPTION
**Pull request by peter279k**
# Changed log
- This is about the organize tests.
- It's related to issue #1.
- This is still in WIP.

### CODE REVIEW

**Comment by Maikuolan** [comment]
(I made a note tonight in the newly added `CONTRIBUTING.md` file, about which branches to target for pull requests, but we can ignore that note for this particular pull request. Because this particular pull request relates to unit tests, and nothing to do with the unit tests has diverged yet in any branches, `master` is okay. Best to continue doing what you're already doing. When everything is done, after this pull request is merged, I can merge it onward into all the other branches locally).

**Comment by Maikuolan** [comment]
@peter279k Just tagging quickly to check that you haven't forgotten about this. :-P

**Comment by peter279k** [comment]
Hi @Maikuolan, thanks for your concern.

I will work on this at my available time.

**Comment by peter279k** [comment]
@Maikuolan, I've initialized the `YAML` and `L10N` tests.

Please review them, thanks.

**Comment by Maikuolan** [comment]
Looks good to me! :+1: :-)

I'll merge it now.

**Pull request merged**
